#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
#  jkdownloader
#  
#  Copyright 2020 Isaac Quiroz <isaac.qa13@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
import searchSerie as sS
import newEpisode as nE
import control

def main():
    
    control.version()
    print('[1] Ver últimos capítulos emitidos.\n')
    print('[2] Buscar Serie.\n')
    print('[3] Exit.\n')
    opt=str(input('Introduzca la opción deseada:\n'))
    if opt=='2':
        sS.main()
    elif opt=='1':
        nE.main()
    elif opt=='3':
        exit()
    else:
        print('Error Valor invalido....')
        control.sleep(2)

if __name__ == '__main__':
    while True:
        main()
